export const metrics = {
  current: {
    hectares: 11.15,
    workers: 16,
    b2bTransactions: 3,
    womenTarget: 100,
    womenActivated: 0,
    revenueFY2025: "751.019.212",
  },
  kpis: [
    {
      id: "hectares",
      label: "Hectares rehabilitated and productively managed",
      current: 11.15,
      target: 20,
      unit: "ha",
      status: "current",
    },
    {
      id: "workers",
      label: "Land and warehouse workers in paid roles",
      current: 16,
      target: null,
      unit: "people",
      status: "current",
    },
    {
      id: "b2b",
      label: "B2B transactions completed",
      current: 3,
      target: null,
      unit: "deals",
      status: "current",
    },
    {
      id: "women",
      label: "Low-income rural women activated (2-year target)",
      current: 0,
      target: 100,
      unit: "women",
      status: "target",
    },
    {
      id: "soil-ph",
      label: "Soil pH improvement (baseline to target)",
      current: null,
      baseline: "acidic",
      target: "neutral range (6.0–7.0)",
      unit: "pH",
      status: "baseline",
    },
    {
      id: "survival",
      label: "Planting survival rate",
      current: null,
      target: 85,
      unit: "%",
      status: "target",
    },
    {
      id: "nursery",
      label: "Nursery seedling output (monthly)",
      current: null,
      target: null,
      unit: "seedlings",
      status: "tracking",
    },
    {
      id: "revenue",
      label: "FY2025 operating revenue",
      current: "IDR 751M",
      target: null,
      unit: "IDR",
      status: "current",
    },
  ],
  impactTracking: [
    "Hectares rehabilitated and productively managed",
    "Soil pH and basic soil-health indicators",
    "Planting survival rate",
    "Vegetation cover",
    "Nursery output",
    "Biomass yield and sales",
    "Recurring buyer contracts",
    "Unique women and local workers trained and paid",
    "Paid workdays",
    "Income generated",
    "Worker retention",
    "Women progressing into team-lead or supplier roles",
  ],
};

export const theoryOfChange = {
  principle:
    "Carbon Bank's theory of change starts from the principle that degraded land will only remain productive when local communities have a recurring economic reason to maintain it.",
  activities: [
    "Rehabilitate degraded and underutilised land",
    "Improve soil condition",
    "Establish nurseries and regenerative forage systems",
    "Organise rural women and local workers into paid roles in planting, land stewardship, harvesting, primary processing and local supply",
  ],
  outputs: [
    "Productive hectares",
    "Improved vegetation",
    "Viable planting materials",
    "Marketable biomass",
    "Paid workdays",
    "Trained workers",
    "Recurring buyer relationships",
  ],
  outcomes: [
    "Women and low-income rural households gain practical skills",
    "Additional income for rural families",
    "Access to commercial agricultural supply chains",
    "Continued land maintenance and expansion beyond the grant period",
  ],
  longTerm:
    "A replicable model in which degraded land becomes a productive environmental and economic asset, women participate in higher-value rural work, and agricultural and livestock businesses gain more reliable access to locally produced biomass.",
};
